# Inserts a blank line between shell prompts
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
#[character]
#success_symbol = "[âœ](bold green) "
#error_symbol = "[âœ](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 5
truncation_symbol = "â€¦/"

# [localip]
# ssh_only = false
# format = "[$localipv4](bold blue) "
# disabled = false

# [username]
# style_user = "green"
# style_root = "bold red"
# format = "[$user]($style)"
# disabled = false
# show_always = true
#
# [hostname]
# ssh_only = false
# ssh_symbol = "ğŸŒ "
# format = "@[$ssh_symbol](bold blue)[$hostname](green) "
# disabled = false
